/// @function scr_changelog_details()
/// @description Returns version history, development TODOs, and known issues.
function scr_changelog_details() {
    return [
        "=== CHANGELOG / TODO / KNOWN ISSUES ===",
        "",
        "[ALPHA v1.1 (PREVIEW BUILD)]",
        "",
        "[LOCALISATION AND DIALOGUE]",
        "+ Added German, Spanish, Polish, Shakespearean.",
        "+ Added Engrish and Japangrish language modes.",
        "+ Localised story scenes and intro dialogue.",
        "+ Added 100+ random multiline Press Start lines.",
        "+ Press Start now blinks on/off without fading.",
        "",
        "[GAMEPLAY AND PRESENTATION]",
        "+ Reworked HUD layout and gem counter display.",
        "+ Stabilised the camera on death and pit falls.",
        "+ Restored visible orange platform walls.",
        "+ Fixed boss movement, damage, and clear flow.",
        "+ Added smooth, NES, mosaic, and black fades.",
        "+ Split physics and camera scroll modes.",
        "+ Added Bootleg Game momentum physics.",
        "+ Polished title, menus, and pause screen.",
        "+ Added pause Options, Jukebox, and leave confirmation.",
        "+ Startup challenge now follows its saved optional setting.",
        "+ Added autosave and Load Recent Game with saved coordinates.",
        "+ Added three named save files and a character name-entry grid.",
        "+ Gameplay autosaves update the active named save file.",
        "+ Added a Time Attack run with a saved best-time record.",
        "+ Saved cheat options now unlock God Mode and every listed stage.",
        "+ Added persistent debug overlay, hitbox outlines, and instant-respawn cheats.",
        "- Removed experimental visual filters after rendering glitches.",
        "+ Fixed dialogue and missing-glyph fallbacks.",
        "",
        "[TODO]",
        "- Finish the Time Attack mode and result screen.",
        "- Add an in-menu guide to gameplay settings.",
        "",
        "[KNOWN ISSUES]",
        "! Bootleg mode intentionally has slippery drift.",
        "! Time Attack is still in prototype form.",
        "",
        "[PROTOTYPE v1.0.1] - 2026-08-30",
        "+ Fixed Time Attack launch with a clear notice.",
        "+ Corrected Dr. Vic Sharp's dialogue narration.",
        "- Removed the old laugh sound effect.",
        "",
        "[ALPHA v1.0.0] - 2026-03-31",
        "+ Added settings, volume controls, fullscreen.",
        "+ Added jukebox and a scrolling changelog.",
        "+ Added room transitions and subtitle support.",
        "",
        "[ALPHA v0.9.0] - 2026-02-15",
        "+ Initial alpha engine and title navigation.",
        "",
		"End of Changelog",
        "--- ---"
    ];
}
