/// @function get_localized_text(key)
/// @description Returns translated string for the saved language, falling back to English.
/// @param {string} _key The key identifier for text
function get_localized_text(_key)
{
    var _text_db = {
        EN: {
            language_select: "SELECT LANGUAGE",
            language_instruction: "LEFT/RIGHT: CHANGE   ENTER: CONFIRM",
            language_setting: "LANGUAGE",
            transition_style: "TRANSITION STYLE",
            fade_style_smooth: "SMOOTH",
            fade_style_nes: "NES",
            fade_style_genesis: "GENESIS BLUE",
            fade_style_mosaic: "MOSAIC",
            fade_style_flash: "ARCADE FLASH",
            fade_style_black: "BLACK HOLD",
            fade_style_off: "OFF / SHOW",
            black_hold_duration: "BLACK HOLD TIME",
            player_physics: "PLAYER PHYSICS",
            scrolling_mode: "SCROLLING MODE",
            physics_default: "DEFAULT",
            physics_jittery: "JITTERY",
            physics_bootleg: "BOOTLEG GAME",
            english: "ENGLISH",
            japanese: "JAPANESE",
            german: "GERMAN",
            spanish: "SPANISH",
            polish: "POLISH (ASCII)",
            shakespearean: "SHAKESPEAREAN",
            engrish: "ENGRISH",
            japangrish: "JAPANGRISH",
            main_menu: "MAIN MENU",
            settings: "SETTINGS",
            cheats_title: "CHEATS",
            play_game: "PLAY GAME",
            load_recent: "LOAD GAME",
            time_attack: "TIME ATTACK",
            autosave_notice: "AUTOSAVE IS ON TO HELP PREVENT LOST PROGRESS.",
            cheats_option: "CHEATS",
            settings_option: "SETTINGS",
            changelog: "CHANGELOG",
            jukebox: "JUKEBOX",
            exit_title: "EXIT TO TITLE SCREEN",
            exit_game: "EXIT GAME",
            bgm_volume: "BGM VOLUME",
            sfx_volume: "SFX VOLUME",
            fullscreen: "FULLSCREEN",
            splash_dialogue: "SPLASH DIALOGUE",
            title_dialogue: "TITLE DIALOGUE",
            arcade_mode: "ARCADE MODE",
            back_to_menu: "BACK TO MENU",
            god_mode: "GOD MODE",
            infinite_ammo: "INFINITE AMMO",
            unlock_levels: "UNLOCK ALL LEVELS",
            on: "ON",
            off: "OFF",
            enabled: "ENABLED",
            disabled: "DISABLED",
            yes: "YES",
            no: "NO",
            press_start: "PRESS START",
            insert_coins: "INSERT COIN",
            credits: "CREDITS",
            startup_challenge: "OPTIONAL STARTUP CHALLENGE",
            challenge_title: "OPTIONAL STARTUP CHALLENGE",
            challenge_enter: "ENTER ANSWER AND PRESS ENTER",
            challenge_granted: "ANSWER ACCEPTED",
            challenge_wrong: "INCORRECT ANSWER",
            challenge_many_wrong: "TOO MANY MISSES. YOU CAN STILL PLAY.",
            challenge_warning_details: "Read the short story, then answer one easy question to continue.",
            challenge_story_continue: "ENTER: NEXT PAGE",
            challenge_story_skip: "ESC: SKIP TO THE QUESTION",
            challenge_story_title: "STORY CHECK",
            challenge_story_question: "HOW MANY MINUTES DID JACK SET THE MICROWAVE?",
            challenge_story_controls: "NUMBER KEYS: TYPE  |  ENTER: ANSWER",
            challenge_solve: "SOLVE THE CHALLENGE:",
            challenge_controls: "TAB: MODE | ARROWS: REROLL | NUMBERS: TYPE | ENTER: SUBMIT",
            difficulty_kids: "KIDS",
            difficulty_adults: "ADULTS",
            history_hint: "[H] HISTORY",
            history_title: "DIALOGUE HISTORY LOG",
            history_close: "Press [H] or [TAB] to Close | Use [UP/DOWN] to Scroll",
            world_label: "WORLD",
            time_label: "TIME",
            game_over: "GAME OVER",
            continue_start: "PRESS START TO CONTINUE",
            pause_title: "PAUSED",
            pause_prompt: "TAKE A BREATHER, THEN CARRY ON",
            pause_controls: "UP/DOWN: MOVE    ENTER: SELECT    ESC: RESUME",
            pause_options: "OPTIONS",
            pause_back: "BACK",
            pause_confirm_title: "LEAVE THIS LEVEL?",
            pause_confirm_yes: "YES, LEAVE",
            pause_confirm_no: "NO, KEEP PLAYING",
            pause_jukebox_help: "UP/DOWN: SELECT   ENTER: PLAY/STOP   ESC: BACK",
            no_credits: "NO CREDITS - INSERT COIN AT TITLE",
            jack_label: "JACK",
            hp_label: "HP",
            score_label: "SCORE",
            gems_label: "GEMS",
            life_lost: "LIFE LOST",
            lives_left: "LIVES LEFT",
            last_life: "LAST LIFE",
            retrying: "RETRYING...",
            "continue": "CONTINUE",
            restart: "RESTART",
            main_menu_exit: "MAIN MENU",
            level_complete: "LEVEL COMPLETE!",
            score_text: "SCORE:",
            time_text: "TIME:",
            press_next: "PRESS START / ENTER TO CONTINUE"
        },
        EG: {
            language_select: "PICK YOUR LANGUAGE THING",
            language_instruction: "LEFT/RIGHT: CHANGE   ENTER: YES",
            language_setting: "LANGUAGE THING",
            transition_style: "FADE STYLE THING",
            fade_style_smooth: "SMOOTH STYLE",
            fade_style_nes: "NES STYLE",
            fade_style_genesis: "GENESIS BLUE STYLE",
            fade_style_mosaic: "MOSAIC BLOCK STYLE",
            fade_style_flash: "ARCADE FLASH STYLE",
            engrish: "ENGRISH",
            japangrish: "JAPANGRISH",
            main_menu: "MAIN MENU PLACE",
            settings: "SETTINGS THINGS",
            play_game: "PLAY THE GAME NOW PLEASE",
            load_recent: "LOAD GAME PLEASE",
            time_attack: "TIME RACE GAME",
            cheats_option: "SECRET HELPINGS",
            settings_option: "SETTING THINGS",
            changelog: "WHAT WAS CHANGED",
            jukebox: "MUSIC BOX MACHINE",
            exit_title: "GO BACK TO TITLE PLACE",
            exit_game: "STOP GAME NOW",
            bgm_volume: "MUSIC LOUD AMOUNT",
            sfx_volume: "SOUND LOUD AMOUNT",
            fullscreen: "BIG FULL SCREEN",
            splash_dialogue: "INTRO TALKING",
            title_dialogue: "TITLE TALKING",
            arcade_mode: "ARCADE GAME MODE",
            back_to_menu: "GO BACK MENU",
            god_mode: "VERY STRONG MODE",
            infinite_ammo: "NEVER END BULLETS",
            unlock_levels: "OPEN ALL LEVEL DOORS",
            on: "YES ON",
            off: "NO OFF",
            enabled: "IT IS ON NOW",
            disabled: "IT IS OFF NOW",
            press_start: "PRESS START BUTTON PLEASE",
            insert_coins: "PUT COIN INSIDE",
            credits: "COIN POINTS",
            challenge_title: "OPTIONAL GAME QUESTION",
            challenge_enter: "WRITE ANSWER THEN PRESS ENTER",
            challenge_granted: "ANSWER IS GOOD",
            challenge_wrong: "ANSWER IS NOT RIGHT",
            challenge_many_wrong: "TOO MANY MISS? YOU CAN STILL PLAY!",
            challenge_warning_details: "Read the story and answer one easy question to continue.",
            challenge_story_continue: "ENTER: NEXT STORY PAGE",
            challenge_story_skip: "ESC: SKIP TO QUESTION",
            challenge_story_title: "STORY QUESTION",
            challenge_story_question: "HOW MANY MINUTES JACK SET MICROWAVE?",
            challenge_story_controls: "NUMBER KEYS: TYPE  |  ENTER: ANSWER",
            continue_start: "PRESS START TO GO AGAIN PLEASE",
            pause_title: "GAME STOP TIME",
            pause_prompt: "Please rest your fingers, they are doing best.",
            pause_controls: "UP/DOWN: MOVE   ENTER: PICK   ESC: GO BACK",
            no_credits: "NO COINS, PLEASE PUT COIN AT TITLE SCREEN",
            jack_label: "JACK HERO",
            hp_label: "HEALTH POWER",
            score_label: "GAME POINTS",
            gems_label: "SHINY ROCKS",
            life_lost: "LIFE HAS GONE AWAY",
            lives_left: "LIVES STILL LEFT",
            last_life: "FINAL LAST LIFE",
            retrying: "TRYING AGAIN NOW...",
            "continue": "CONTINUE PLEASE",
            restart: "START OVER AGAIN",
            main_menu_exit: "MAIN MENU PLACE",
            level_complete: "LEVEL IS FINISHED GOOD!",
            score_text: "POINTS:",
            time_text: "TIME AMOUNT:"
        },
        JG: {
            language_select: "LANGUAGE SELECT PLEASE",
            language_instruction: "LEFT/RIGHT: CHANGE SIGN   ENTER: OKAY",
            language_setting: "LANGUAGE SIGN",
            transition_style: "SCREEN CHANGE STYLE",
            fade_style_smooth: "SMOOTH FADE MODE",
            fade_style_nes: "NES SCREEN STYLE",
            fade_style_genesis: "BLUE GENESIS STYLE",
            fade_style_mosaic: "MOSAIC BLOCK STYLE",
            fade_style_flash: "FLASHING ARCADE STYLE",
            engrish: "ENGRISH",
            japangrish: "JAPANGRISH",
            main_menu: "MAIN MENU DIRECTION",
            settings: "SETTINGS BOX",
            play_game: "PLAY GAME, YES",
            load_recent: "LOAD GAME DATA",
            time_attack: "TIME ATTACK RACE",
            cheats_option: "SECRET POWER",
            settings_option: "SETTINGS BOX",
            changelog: "CHANGE RECORD PAPER",
            jukebox: "MUSIC LISTEN BOX",
            exit_title: "RETURN TITLE SCREEN, PLEASE",
            exit_game: "GAME END BUTTON",
            bgm_volume: "MUSIC SOUND BIGNESS",
            sfx_volume: "EFFECT SOUND BIGNESS",
            fullscreen: "FULL SCREEN MODE",
            splash_dialogue: "OPENING TALK SIGN",
            title_dialogue: "TITLE TALK SIGN",
            arcade_mode: "ARCADE GAME STYLE",
            back_to_menu: "BACK TO MENU ROAD",
            god_mode: "GOD POWER MODE",
            infinite_ammo: "BULLET NEVER END",
            unlock_levels: "OPEN ALL STAGE DOORS",
            on: "ON DESU",
            off: "OFF DESU",
            enabled: "POWER IS ON",
            disabled: "POWER IS NOT ON",
            press_start: "PRESS START PLEASE, FRIEND",
            insert_coins: "INSERT COIN INTO HOLE",
            credits: "COIN NUMBER",
            challenge_title: "OPTIONAL CHALLENGE SIGN",
            challenge_enter: "TYPE ANSWER AND PRESS ENTER, PLEASE",
            challenge_granted: "ANSWER IS CORRECT, GOOD",
            challenge_wrong: "ANSWER IS WRONG, SORRY",
            challenge_many_wrong: "MANY WRONG? YOU CAN STILL PLAY GAME!",
            challenge_warning_details: "Read story and answer one easy question to start the game.",
            challenge_story_continue: "ENTER: NEXT STORY SIGN",
            challenge_story_skip: "ESC: GO TO QUESTION",
            challenge_story_title: "STORY QUESTION TIME",
            challenge_story_question: "HOW MANY MINUTES JACK SET MICROWAVE?",
            challenge_story_controls: "NUMBER KEY: TYPE  |  ENTER: ANSWER",
            continue_start: "PRESS START TO CONTINUE ROAD",
            pause_title: "PAUSE TIME, PLEASE",
            pause_prompt: "No running! The boss is also on break.",
            pause_controls: "UP/DOWN: MOVE   ENTER: CHOOSE   ESC: RETURN",
            no_credits: "NO COIN. PLEASE INSERT COIN AT TITLE SIGN",
            jack_label: "JACK PERSON",
            hp_label: "HEALTH POINT",
            score_label: "SCORE NUMBER",
            gems_label: "GEM ROCKS",
            life_lost: "LIFE IS LOST, SORRY",
            lives_left: "LIFE NUMBERS LEFT",
            last_life: "LAST LIFE NUMBER",
            retrying: "TRY AGAIN PLEASE...",
            "continue": "CONTINUE ROAD",
            restart: "RESTART THE GAME AGAIN",
            main_menu_exit: "MAIN MENU DIRECTION",
            level_complete: "STAGE CLEAR, VERY GOOD!",
            score_text: "SCORE NUMBER:",
            time_text: "TIME NUMBER:"
        },
        ES: {
            language_select: "ELIGE IDIOMA",
            language_instruction: "IZQ./DER.: CAMBIAR   ENTER: ELEGIR",
            language_setting: "IDIOMA",
            transition_style: "ESTILO DE TRANSICIÓN",
            fade_style_smooth: "SUAVE",
            fade_style_nes: "NES",
            fade_style_genesis: "AZUL GENESIS",
            fade_style_mosaic: "MOSAICO",
            fade_style_flash: "DESTELLO ARCADE",
            english: "INGLÉS",
            german: "ALEMÁN",
            spanish: "ESPAÑOL",
            polish: "POLACO (ASCII)",
            shakespearean: "SHAKESPEARIANO",
            engrish: "ENGRISH",
            japangrish: "JAPANGRISH",
            main_menu: "MENÚ PRINCIPAL",
            settings: "OPCIONES",
            cheats_title: "TRUCOS",
            play_game: "JUGAR",
            load_recent: "CARGAR PARTIDA",
            time_attack: "CONTRARRELOJ",
            cheats_option: "TRUCOS",
            settings_option: "OPCIONES",
            changelog: "CAMBIOS",
            jukebox: "MÚSICA",
            exit_title: "VOLVER AL TÍTULO",
            exit_game: "SALIR DEL JUEGO",
            bgm_volume: "VOLUMEN DE MÚSICA",
            sfx_volume: "VOLUMEN DE EFECTOS",
            fullscreen: "PANTALLA COMPLETA",
            splash_dialogue: "DIÁLOGO INICIAL",
            title_dialogue: "DIÁLOGO DEL TÍTULO",
            arcade_mode: "MODO ARCADE",
            back_to_menu: "VOLVER AL MENÚ",
            god_mode: "MODO DIOS",
            infinite_ammo: "MUNICIÓN INFINITA",
            unlock_levels: "DESBLOQUEAR NIVELES",
            on: "SÍ",
            off: "NO",
            enabled: "ACTIVADO",
            disabled: "DESACTIVADO",
            yes: "SÍ",
            no: "NO",
            press_start: "PULSA START",
            insert_coins: "INSERTA UNA MONEDA",
            credits: "CRÉDITOS",
            startup_challenge: "RETO OPCIONAL",
            challenge_title: "RETO OPCIONAL",
            challenge_enter: "ESCRIBE LA RESPUESTA Y PULSA ENTER",
            challenge_granted: "RESPUESTA CORRECTA",
            challenge_wrong: "RESPUESTA INCORRECTA",
            challenge_many_wrong: "MUCHOS ERRORES? AUN PUEDES JUGAR!",
            challenge_warning_details: "Lee la historia y responde una pregunta sencilla para continuar.",
            challenge_story_continue: "ENTER: SIGUIENTE PAGINA",
            challenge_story_skip: "ESC: IR A LA PREGUNTA",
            challenge_story_title: "PREGUNTA DE LA HISTORIA",
            challenge_story_question: "CUANTOS MINUTOS PUSO JACK?",
            challenge_story_controls: "NUMEROS: ESCRIBIR  |  ENTER: RESPONDER",
            challenge_solve: "RESUELVE EL RETO:",
            difficulty_kids: "NIÑOS",
            difficulty_adults: "ADULTOS",
            world_label: "MUNDO",
            time_label: "TIEMPO",
            game_over: "FIN DEL JUEGO",
            continue_start: "PULSA START PARA CONTINUAR",
            pause_title: "EN PAUSA",
            pause_prompt: "TOMA UN RESPIRO Y SIGUE",
            pause_controls: "ARRIBA/ABAJO: MOVER   ENTER: ELEGIR   ESC: SEGUIR",
            no_credits: "SIN CRÉDITOS: INSERTA UNA MONEDA EN EL TÍTULO",
            jack_label: "JACK",
            hp_label: "VIDA",
            score_label: "PUNTOS",
            gems_label: "GEMAS",
            life_lost: "VIDA PERDIDA",
            lives_left: "VIDAS RESTANTES",
            last_life: "ÚLTIMA VIDA",
            retrying: "REINTENTANDO...",
            "continue": "CONTINUAR",
            restart: "REINICIAR",
            main_menu_exit: "MENÚ PRINCIPAL",
            level_complete: "¡NIVEL COMPLETADO!",
            score_text: "PUNTOS:",
            time_text: "TIEMPO:",
            press_next: "PULSA START / ENTER PARA CONTINUAR"
        },
        DE: {
            language_select: "SPRACHE WÄHLEN",
            language_instruction: "LINKS/RECHTS: ÄNDERN   ENTER: BESTÄTIGEN",
            language_setting: "SPRACHE",
            transition_style: "ÜBERGANGSSTIL",
            fade_style_smooth: "SANFT",
            fade_style_nes: "NES",
            fade_style_genesis: "GENESIS-BLAU",
            fade_style_mosaic: "MOSAIK",
            fade_style_flash: "ARCADE-BLITZ",
            english: "ENGLISCH",
            german: "DEUTSCH",
            spanish: "SPANISCH",
            polish: "POLNISCH (ASCII)",
            shakespearean: "SHAKESPEARE",
            engrish: "ENGRISH",
            japangrish: "JAPANGRISH",
            main_menu: "HAUPTMENÜ",
            settings: "EINSTELLUNGEN",
            cheats_title: "CHEATS",
            play_game: "SPIEL STARTEN",
            load_recent: "SPIEL LADEN",
            time_attack: "ZEITANGRIFF",
            cheats_option: "CHEATS",
            settings_option: "EINSTELLUNGEN",
            changelog: "ÄNDERUNGEN",
            jukebox: "MUSIKBOX",
            exit_title: "ZUM TITELBILDSCHIRM",
            exit_game: "SPIEL BEENDEN",
            bgm_volume: "MUSIKLAUTSTÄRKE",
            sfx_volume: "EFFEKTAUTSTÄRKE",
            fullscreen: "VOLLBILDSCHIRM",
            splash_dialogue: "VORSPANN-DIALOG",
            title_dialogue: "TITEL-DIALOG",
            arcade_mode: "ARCADE-MODUS",
            back_to_menu: "ZUM MENÜ",
            god_mode: "GOTT-MODUS",
            infinite_ammo: "UNENDLICHE MUNITION",
            unlock_levels: "ALLE LEVEL FREISCHALTEN",
            on: "AN",
            off: "AUS",
            enabled: "AKTIVIERT",
            disabled: "DEAKTIVIERT",
            yes: "JA",
            no: "NEIN",
            press_start: "START DRÜCKEN",
            insert_coins: "MÜNZE EINWERFEN",
            credits: "GUTHABEN",
            startup_challenge: "OPTIONALE START-HERAUSFORDERUNG",
            challenge_title: "OPTIONALE START-HERAUSFORDERUNG",
            challenge_enter: "ANTWORT EINGEBEN UND ENTER DRÜCKEN",
            challenge_granted: "ANTWORT AKZEPTIERT",
            challenge_wrong: "FALSCHE ANTWORT",
            challenge_many_wrong: "ZU VIELE FEHLER? DU KANNST TROTZDEM SPIELEN!",
            challenge_warning_details: "Lies die kurze Geschichte und beantworte eine einfache Frage.",
            challenge_story_continue: "ENTER: WEITER",
            challenge_story_skip: "ESC: DIREKT ZUR FRAGE",
            challenge_story_title: "GESCHICHTSFRAGE",
            challenge_story_question: "WIE VIELE MINUTEN STELLTE JACK EIN?",
            challenge_story_controls: "ZAHLENTASTEN: EINGABE  |  ENTER: ANTWORT",
            challenge_solve: "LÖSE DIE HERAUSFORDERUNG:",
            difficulty_kids: "KINDER",
            difficulty_adults: "ERWACHSENE",
            world_label: "WELT",
            time_label: "ZEIT",
            game_over: "SPIEL VORBEI",
            continue_start: "START ZUM WEITERSPIELEN",
            pause_title: "PAUSE",
            pause_prompt: "ATME KURZ DURCH UND SPIELE WEITER",
            pause_controls: "HOCH/RUNTER: WÄHLEN   ENTER: BESTÄTIGEN   ESC: WEITER",
            no_credits: "KEIN GUTHABEN - MÜNZE AM TITELBILDSCHIRM EINWERFEN",
            jack_label: "JACK",
            hp_label: "LP",
            score_label: "PUNKTE",
            gems_label: "JUWELEN",
            life_lost: "LEBEN VERLOREN",
            lives_left: "LEBEN ÜBRIG",
            last_life: "LETZTES LEBEN",
            retrying: "NEUER VERSUCH...",
            "continue": "WEITER",
            restart: "NEUSTART",
            main_menu_exit: "HAUPTMENÜ",
            level_complete: "LEVEL GESCHAFFT!",
            score_text: "PUNKTE:",
            time_text: "ZEIT:",
            press_next: "START / ENTER ZUM WEITERGEHEN"
        },
        PL: {
            language_select: "WYBIERZ JEZYK",
            language_instruction: "LEWO/PRAWO: ZMIEN   ENTER: WYBIERZ",
            language_setting: "JEZYK",
            transition_style: "STYL PRZEJSCIA",
            fade_style_smooth: "PLYNNY",
            fade_style_nes: "NES",
            fade_style_genesis: "GENESIS NIEBIESKI",
            fade_style_mosaic: "MOZAIKA",
            fade_style_flash: "BLYSK ARCADE",
            english: "ANGIELSKI",
            german: "NIEMIECKI",
            spanish: "HISZPANSKI",
            polish: "POLSKI (ASCII)",
            shakespearean: "SZEKSPIROWSKI",
            engrish: "ENGRISH",
            japangrish: "JAPANGRISH",
            main_menu: "MENU GLOWNE",
            settings: "USTAWIENIA",
            cheats_title: "KODY",
            play_game: "GRAJ",
            load_recent: "WCZYTAJ GRE",
            time_attack: "PROBA CZASU",
            cheats_option: "KODY",
            settings_option: "USTAWIENIA",
            changelog: "ZMIANY",
            jukebox: "SZAFUJKE",
            exit_title: "DO EKRANU TYTULOWEGO",
            exit_game: "WYJDZ Z GRY",
            bgm_volume: "GLOSNOSC MUZYKI",
            sfx_volume: "GLOSNOSC EFEKTOW",
            fullscreen: "PELNY EKRAN",
            splash_dialogue: "DIALOG W INTRO",
            title_dialogue: "DIALOG TYTULOWY",
            arcade_mode: "TRYB ARCADE",
            back_to_menu: "WROC DO MENU",
            god_mode: "TRYB BOGA",
            infinite_ammo: "NIESKONCZONA AMUNICJA",
            unlock_levels: "ODBLOKUJ WSZYSTKIE POZIOMY",
            on: "WL",
            off: "WYL",
            enabled: "WLACZONE",
            disabled: "WYLACZONE",
            yes: "TAK",
            no: "NIE",
            press_start: "NACISNIJ START",
            insert_coins: "WRZUC MONETE",
            credits: "KREDYTY",
            startup_challenge: "DODATKOWE WYZWANIE",
            challenge_title: "DODATKOWE WYZWANIE",
            challenge_enter: "WPISZ ODPOWIEDZ I NACISNIJ ENTER",
            challenge_granted: "DOBRA ODPOWIEDZ",
            challenge_wrong: "ZLA ODPOWIEDZ",
            challenge_many_wrong: "ZA DUZO BLEDOW? NADAL MOZESZ GRAC!",
            challenge_warning_details: "Przeczytaj krotka historie i odpowiedz na jedno latwe pytanie.",
            challenge_story_continue: "ENTER: DALEJ",
            challenge_story_skip: "ESC: PRZEJDZ DO PYTANIA",
            challenge_story_title: "PYTANIE Z HISTORII",
            challenge_story_question: "NA ILE MINUT JACK USTAWIL MIKROFALE?",
            challenge_story_controls: "CYFRY: WPISZ  |  ENTER: ODPOWIEDZ",
            challenge_solve: "ROZWIAZ ZADANIE:",
            difficulty_kids: "DZIECI",
            difficulty_adults: "DOROSLI",
            world_label: "SWIAT",
            time_label: "CZAS",
            game_over: "KONIEC GRY",
            continue_start: "NACISNIJ START, ABY GRAC DALEJ",
            pause_title: "PAUZA",
            pause_prompt: "ODPOCZNIJ CHWILE I GRAJ DALEJ",
            pause_controls: "GORA/DOL: RUCH   ENTER: WYBIERZ   ESC: WROC",
            no_credits: "BRAK KREDYTOW - WRZUC MONETE NA EKRANIE TYTULOWYM",
            jack_label: "JACK",
            hp_label: "HP",
            score_label: "WYNIK",
            gems_label: "KAMIENIE",
            life_lost: "UTRACONO ZYCIE",
            lives_left: "POZOSTALE ZYCIA",
            last_life: "OSTATNIE ZYCIE",
            retrying: "PONOWNA PROBA...",
            "continue": "DALEJ",
            restart: "OD NOWA",
            main_menu_exit: "MENU GLOWNE",
            level_complete: "POZIOM UKONCZONY!",
            score_text: "WYNIK:",
            time_text: "CZAS:",
            press_next: "START / ENTER, ABY KONTYNUOWAC"
        },
        SH: {
            language_select: "CHOOSE THY TONGUE",
            language_instruction: "LEFT/RIGHT: CHANGE   ENTER: CONFIRM",
            language_setting: "TONGUE",
            transition_style: "MANNER OF PASSAGE",
            fade_style_smooth: "GENTLE",
            fade_style_nes: "NES",
            fade_style_genesis: "GENESIS BLUE",
            fade_style_mosaic: "MOSAIC",
            fade_style_flash: "ARCADE FLASH",
            english: "ENGLISH",
            german: "GERMAN",
            spanish: "SPANISH",
            polish: "POLISH (ASCII)",
            shakespearean: "SHAKESPEAREAN",
            engrish: "ENGRISH",
            japangrish: "JAPANGRISH",
            main_menu: "THE GRAND MENU",
            settings: "SETTINGS",
            cheats_title: "CHEATS",
            play_game: "BEGIN THY QUEST",
            load_recent: "LOAD THY GAME",
            time_attack: "RACE AGAINST TIME",
            cheats_option: "CHEATS",
            settings_option: "SETTINGS",
            changelog: "WHAT IS NEW",
            jukebox: "MUSIC BOX",
            exit_title: "RETURN TO TITLE",
            exit_game: "QUIT THIS REALM",
            bgm_volume: "TUNE THE MUSIC",
            sfx_volume: "TUNE THE EFFECTS",
            fullscreen: "FULL SCREEN",
            splash_dialogue: "OPENING DIALOGUE",
            title_dialogue: "TITLE DIALOGUE",
            arcade_mode: "ARCADE MODE",
            back_to_menu: "BACK TO MENU",
            god_mode: "GOD MODE",
            infinite_ammo: "ENDLESS AMMUNITION",
            unlock_levels: "UNLOCK EVERY LEVEL",
            on: "AYE",
            off: "NAY",
            enabled: "ENABLED",
            disabled: "DISABLED",
            yes: "AYE",
            no: "NAY",
            press_start: "PRESS START, GOOD FELLOW",
            insert_coins: "CAST IN A COIN",
            credits: "COIN PURSE",
            startup_challenge: "OPTIONAL TRIAL",
            challenge_title: "OPTIONAL TRIAL",
            challenge_enter: "WRITE THY ANSWER AND PRESS ENTER",
            challenge_granted: "WELL ANSWERED",
            challenge_wrong: "THAT ANSWER IS AMISS",
            challenge_many_wrong: "TOO MANY MISSES? THOU MAYST STILL PLAY!",
            challenge_warning_details: "Read the tale and answer one easy question to continue thy quest.",
            challenge_story_continue: "ENTER: TURN THE PAGE",
            challenge_story_skip: "ESC: HASTEN TO THE QUESTION",
            challenge_story_title: "A QUESTION OF THE TALE",
            challenge_story_question: "HOW MANY MINUTES DID JACK SET THE MICROWAVE?",
            challenge_story_controls: "NUMBER KEYS: WRITE  |  ENTER: ANSWER",
            challenge_solve: "SOLVE THIS RIDDLE:",
            difficulty_kids: "YOUNG FOLK",
            difficulty_adults: "GROWN FOLK",
            world_label: "REALM",
            time_label: "TIME",
            game_over: "THY QUEST HATH ENDED",
            continue_start: "PRESS START TO CONTINUE THY QUEST",
            pause_title: "A MOMENT'S RESPITE",
            pause_prompt: "Merry? Shall we have a play extempore?",
            pause_controls: "UP/DOWN: MOVE    ENTER: CHOOSE    ESC: RETURN",
            no_credits: "NO COINS - CAST ONE IN AT THE TITLE",
            jack_label: "JACK",
            hp_label: "HP",
            score_label: "SCORE",
            gems_label: "GEMS",
            life_lost: "A LIFE IS LOST",
            lives_left: "LIVES REMAINING",
            last_life: "THY LAST LIFE",
            retrying: "TRY ONCE MORE...",
            "continue": "CONTINUE",
            restart: "BEGIN ANEW",
            main_menu_exit: "THE GRAND MENU",
            level_complete: "THOU HAST WON THIS LEVEL!",
            score_text: "SCORE:",
            time_text: "TIME:",
            press_next: "PRESS START / ENTER TO PROCEED"
        },
        JP: {
            language_select: "コトバヲ エランデクダサイ",
            language_instruction: "LEFT/RIGHT: センタク   ENTER: ケッテイ",
            language_setting: "コトバ",
            english: "エイゴ",
            japanese: "ニホンゴ",
            main_menu: "メインメニュー",
            settings: "セッテイ",
            cheats_title: "チート",
            play_game: "ゲームヲ ハジメル",
            load_recent: "ロードゲーム",
            time_attack: "タイムアタック",
            cheats_option: "チート",
            settings_option: "セッテイ",
            changelog: "コウシン キロク",
            jukebox: "ジュークボックス",
            exit_title: "タイトルヘ モドル",
            exit_game: "ゲームヲ オワル",
            bgm_volume: "BGM オンリョウ",
            sfx_volume: "SFX オンリョウ",
            fullscreen: "フルスクリーン",
            splash_dialogue: "スプラッシュ セリフ",
            title_dialogue: "タイトル セリフ",
            arcade_mode: "アーケード モード",
            back_to_menu: "メニューヘ モドル",
            god_mode: "ゴッド モード",
            infinite_ammo: "ムゲン ダンヤク",
            unlock_levels: "スベテノ レベル",
            on: "オン",
            off: "オフ",
            enabled: "オン",
            disabled: "オフ",
            yes: "ハイ",
            no: "イイエ",
            press_start: "ENTER キーデ ハジメル",
            insert_coins: "コインヲ イレテクダサイ",
            credits: "クレジット",
            startup_challenge: "オプション チャレンジ",
            challenge_title: "オプション チャレンジ",
            challenge_enter: "コタエヲ イレテ ENTER",
            challenge_granted: "セイカイ",
            challenge_wrong: "マチガイデス",
            challenge_solve: "コタエテクダサイ:",
            challenge_controls: "TAB: モード | ARROWS: ツクリナオス | NUMBERS: ニュウリョク | ENTER: ケッテイ",
            difficulty_kids: "キッズ",
            difficulty_adults: "アダルト",
            history_hint: "[H] カイワノ キロク",
            history_title: "カイワノ キロク",
            history_close: "[H] マタハ [TAB] デ トジル | UP/DOWN デ スクロール",
            world_label: "ワールド",
            time_label: "タイム",
            game_over: "ゲームオーバー",
            continue_start: "START デ ツヅケル",
            no_credits: "クレジットガ アリマセン",
            jack_label: "ジャック",
            hp_label: "HP",
            score_label: "スコア",
            gems_label: "ジェム",
            life_lost: "ライフ ロスト",
            lives_left: "ノコリ ライフ",
            last_life: "ラスト ライフ",
            retrying: "リトライ...",
            "continue": "ツヅケル",
            restart: "ヤリナオス",
            main_menu_exit: "メインメニュー",
            level_complete: "ステージ クリア!",
            score_text: "スコア:",
            time_text: "タイム:",
            press_next: "スタート マタハ エンター デ ツギヘ"
        }
    };

    // Fallback logic if language or key is missing
    var _language = variable_global_exists("language") ? global.language : "EN";
    if (variable_struct_exists(_text_db, _language))
    {
        var _lang_struct = variable_struct_get(_text_db, _language);
        if (variable_struct_exists(_lang_struct, _key))
        {
            return variable_struct_get(_lang_struct, _key);
        }
    }
    
    if (variable_struct_exists(_text_db.EN, _key)) {
        return variable_struct_get(_text_db.EN, _key);
    }
    return _key;
}
