/// @function scr_get_random_press_start_message()
/// @description Returns a random humorous title-screen message. Literal \\n markers become line breaks when drawn.
function scr_get_random_press_start_message() {
    var _messages = [
        "Don't be shy, little one!\\nPress Start and your mighty quest will begin!",
        "The kingdom is waiting.\\nIt has been waiting for quite a while.",
        "Press Start! The monsters promised\\nto be only a little bit scary.",
        "Your heroic destiny is calling.\\nIt left three very polite messages.",
        "A mighty quest awaits!\\nSnacks are optional but recommended.",
        "Press Start to begin.\\nPress snacks to continue snacking.",
        "The hero has arrived!\\nThe hero is you. Please act surprised.",
        "The kingdom needs saving.\\nIts calendar is getting awkward.",
        "Adventure awaits beyond this screen.\\nIt says hello, by the way.",
        "Press Start and be a hero!\\nCape not included. Dramatic pose is.",
        "The villain is making plans.\\nMostly seating arrangements.",
        "A prophecy mentioned you.\\nIt was written on a very small napkin.",
        "Press Start! The quest begins!\\nThe paperwork can wait.",
        "The castle is in trouble.\\nAgain. Castles, honestly.",
        "Your adventure is ready.\\nIt brought a map and lost the map.",
        "The monsters are nervous.\\nOne of them is holding a tiny shield.",
        "Press Start to make history!\\nPreferably the good kind.",
        "A kingdom needs a champion.\\nThe interview is just this button.",
        "Your boots are tied.\\nYour heroic destiny is slightly untied.",
        "Press Start! The world awaits!\\nIt has prepared a welcome mat.",
        "The quest called.\\nIt says you sound very promising.",
        "You look mighty enough.\\nThe hat is doing most of the work.",
        "Press Start and explore!\\nTry not to adopt every monster.",
        "The royal trumpet is ready.\\nThe trumpet player is still warming up.",
        "A great adventure begins now.\\nOr after you press Start.",
        "Your legend is unwritten.\\nThe pencil is sharpened.",
        "The dragon heard you were coming.\\nIt baked a very nervous cake.",
        "Press Start! Glory awaits!\\nSo does a suspiciously large door.",
        "The map says go north.\\nThe map also says it is upside down.",
        "A mighty hero needs courage.\\nAnd maybe a small lunch.",
        "The kingdom has one request.\\nPlease press the big imaginary button.",
        "Press Start to begin your quest.\\nThe quest has excellent manners.",
        "The royal guard is ready.\\nOne guard is a very alert pigeon.",
        "Adventure is just around the corner.\\nIt may be a very large corner.",
        "The boss is waiting.\\nIt brought a chair and a backup chair.",
        "Press Start! Your story begins!\\nThere may be a dramatic soundtrack.",
        "The kingdom believes in you.\\nThe kingdom also believes in soup.",
        "Your sword is polished.\\nYour heroic face is almost polished.",
        "A mysterious quest awaits.\\nIt left the mystery in the other room.",
        "Press Start to save the day!\\nThe day has been very patient.",
        "The path to glory is open.\\nMind the welcome mat.",
        "The villagers are cheering.\\nOne is cheering for lunch.",
        "Your destiny is ready.\\nIt brought a spare destiny just in case.",
        "Press Start! Be legendary!\\nSmall legends are still legends.",
        "A monster stole the royal cheese.\\nThis has become surprisingly serious.",
        "The castle bells are ringing.\\nOne bell is just excited.",
        "Your quest starts with one press.\\nYour enemies start with none.",
        "The hero-shaped vacancy is yours.\\nNo experience required.",
        "Press Start and meet your fate!\\nFate says it is nice to meet you.",
        "The kingdom needs your help.\\nThe king is busy naming a sandwich.",
        "Your adventure awaits!\\nIt has packed sensible walking shoes.",
        "The dungeon is ready.\\nIt cleaned up a little. Not much.",
        "Press Start to begin!\\nThe pause button is also very supportive.",
        "A hero's journey begins here.\\nThe hero may bring a friend.",
        "The royal wizard says press Start.\\nThe royal wizard says many things.",
        "Your quest is loading.\\nThe loading screen is on vacation.",
        "The monsters have a meeting today.\\nYou are probably on the agenda.",
        "Press Start! Destiny awaits!\\nDestiny brought a clipboard.",
        "The king has a quest for you.\\nHe promises it is mostly safe.",
        "Your boots are adventure-ready.\\nThe left one is especially excited.",
        "The treasure is out there.\\nIt has been practicing its hiding.",
        "Press Start and set off!\\nThe map says 'good luck' in crayon.",
        "The hero committee has voted.\\nYou got the job unanimously.",
        "The kingdom is counting on you.\\nIt is not great at counting.",
        "Your shield is ready.\\nIt has been practicing its brave face.",
        "Adventure called again.\\nIt says it can wait one more second.",
        "Press Start to begin the quest!\\nThe quest has brought biscuits.",
        "The castle gate is open.\\nThe gate says please come in.",
        "A legendary hero is needed.\\nYou have excellent legendary potential.",
        "The dragon is guarding treasure.\\nIt is also guarding its lunch.",
        "Press Start! Time to be mighty!\\nTiny mighty still counts.",
        "The royal map is accurate.\\nExcept for the doodles.",
        "The villain is almost ready.\\nThey are fixing their dramatic cape.",
        "A grand quest begins soon.\\nSoon is approximately one button press.",
        "The villagers have prepared a feast.\\nIt is mostly turnips. Sorry.",
        "Press Start to begin your legend!\\nPlease spell your name correctly.",
        "Your heroic soundtrack is queued.\\nThe kazoo solo is optional.",
        "The dungeon has excellent lighting.\\nIt is mostly torches.",
        "The kingdom needs a brave hero.\\nThe brave part can happen gradually.",
        "Press Start! Adventure awaits!\\nIt is wearing a tiny helmet.",
        "Your sword says hello.\\nIt is not great at conversation.",
        "The royal chef packed a lunch.\\nThe royal chef packed it for themself.",
        "A treasure chest is waiting.\\nIt insists it is not a mimic.",
        "Your quest starts right here.\\nThe shoes start just over there.",
        "Press Start and save the kingdom!\\nThe kingdom says thank you in advance.",
        "The monsters are warming up.\\nTheir stretching is quite impressive.",
        "The great adventure is ready.\\nIt remembered to bring a map this time.",
        "A hero walks into a castle...\\nPress Start to hear the rest.",
        "The royal messenger arrived.\\nThey forgot the message. Classic.",
        "Press Start! Your quest awaits!\\nIt has been doing warm-up stretches.",
        "The crown is shiny.\\nThe king says it is not a quest reward.",
        "Your destiny is calling.\\nIt has a very dramatic ringtone.",
        "The kingdom needs a champion.\\nThe champion gets first pick of snacks.",
        "Press Start to begin the adventure!\\nThe adventure promises to use its inside voice.",
        "The boss has a weakness.\\nIt might be compliments. Worth a try.",
        "A brave new quest awaits.\\nIt has packed a spare pair of socks.",
        "The royal horses are ready.\\nOne horse would rather be a painter.",
        "Press Start! The quest begins!\\nThe dramatic entrance is up to you.",
        "A mysterious door stands ahead.\\nIt has a very ordinary handle.",
        "The wizard prepared a spell.\\nIt is mostly glitter. Probably safe.",
        "Your legend starts with a button.\\nThat is pretty convenient, actually.",
        "The kingdom has sent a pigeon.\\nThe pigeon has sent itself instead.",
        "Press Start and claim your destiny!\\nReceipt available upon request.",
        "The treasure is nearly yours.\\nThe treasure has not been informed.",
        "A mighty quest is just ahead.\\nIt brought a tiny compass.",
        "The royal blacksmith is ready.\\nThe anvil has been briefed too.",
        "Press Start! The world needs you!\\nThe world also needs a nap.",
        "Your courage is impressive.\\nYour posture could use a quest.",
        "The castle is full of secrets.\\nOne is where they keep the brooms.",
        "A hero's work is never done.\\nFortunately, it has not started yet.",
        "Press Start to begin!\\nYour future self says thanks.",
        "The monsters made a welcome sign.\\nThey spelled 'welcome' correctly.",
        "Your adventure starts now.\\nThe snacks start whenever you do.",
        "The king requests your presence.\\nThe king requests many things.",
        "Press Start and go be mighty!\\nThe word 'mighty' is very encouraging.",
        "The dungeon has a gift shop.\\nIt sells slightly used torches.",
        "Your quest awaits beyond the title.\\nIt is trying to look mysterious.",
        "The royal trumpet says ta-da!\\nIt is still learning the notes.",
        "The hero's cape is ready.\\nThe cape has its own fan club.",
        "Press Start! Glory is near!\\nNear-ish. The map is a little vague.",
        "A dragon guards the treasure.\\nThe dragon also guards personal space.",
        "The kingdom has high hopes.\\nAnd a backup plan involving soup.",
        "Your mighty quest is waiting.\\nIt brought its own tiny flag.",
        "Press Start and make your mark!\\nPreferably not on the castle wall.",
        "The guards are ready to cheer.\\nOne guard is still learning the words.",
        "A hero was needed.\\nYou were the first one near the button.",
        "The royal library has a quest book.\\nIt is overdue, like every other book.",
        "Press Start! Your story awaits!\\nThe opening chapter is very button-shaped.",
        "The monsters are prepared.\\nThey brought snacks for after the battle.",
        "A new adventure is on the horizon.\\nThe horizon looks very adventurous.",
        "Your quest begins with confidence.\\nOr a button. Both are good.",
        "The king says hurry up.\\nThe king is bad at waiting.",
        "Press Start and become a legend!\\nA humble legend, if possible.",
        "The treasure map is ready.\\nThe treasure map is upside down again.",
        "The kingdom believes in you.\\nEven the grumpy gate believes in you.",
        "Your adventure is just one press away.\\nThe button is feeling important.",
        "Press Start! The quest is calling!\\nIt sounds a little like a kazoo.",
        "The royal chef packed you a pie.\\nThe pie packed itself a tiny sword.",
        "The dungeon awaits its hero.\\nIt swept the floor. Mostly.",
        "A mighty quest is about to begin.\\nPlease keep hands inside the adventure.",
        "Press Start to save the day!\\nThe day says it could use the help.",
        "Your heroic boots are laced.\\nYour heroic snacks are not.",
        "The boss is practicing its roar.\\nIt sounds a bit like a sneeze.",
        "The kingdom's fate rests with you.\\nNo pressure. Actually, a little pressure.",
        "Press Start and begin your mighty quest!\\nThe tiny fanfare is standing by."
    ];

    var _message = _messages[irandom(array_length(_messages) - 1)];
    if (string_pos("PRESS START", string_upper(_message)) == 0) {
        _message += "\\nPress Start!";
    }

    return _message;
}
