/// @description scr_credits()
/// @return {Array} Cleaned text array optimized for dynamic layout engines
function scr_credits() {
    var _manifest = [
        "================================================================",
        "YOUR ODYSSEY REPRESENTS MAGNIFICENCE.",
        "",
        "CONGRATULATIONS. THIS CHRONICLE CONCLUDES IN TRIUMPH.",
        "",
        "YOU HAVE SAVED EVERY INNOCENT SOUL OF AETHERIA!",
        "YOU HAVE SUCCESSFULLY SAVED THE UNIVERSE FROM FALLING INTO",
        "THE SACRED HANDS OF DR. VICTOR SCHADENFREUDE AND HIS FALSE FAMILY!",
        "AS OF NOW, WE BID YOU A GRAND FAREWELL TO THIS MIGHTY ADVENTURE!",
        "BUT WAIT, MORE MISSIONS ARE AHEAD!",
        "JACK'S MIGHTY QUEST (TM) v1.0 Full Release - COMING SOON!",
        "",
        "",
        "To the Player:",
        "",
        "We offer our most profound and heartfelt gratitude for choosing the path of peace.",
        "",
        "In a world so often torn apart by discord and strife, your steadfast resolve to seek harmony, to protect precious life, and to walk without malice represents the highest peak of true valor.",
        "",
        "You have proven completely that true strength lies not in the base power to lay waste and destroy, but in the noble courage to protect, to preserve, and to restore.",
        "",
        "We thank you deeply for binding together the hopes, the dreams, and the sweet aspirations of the multitude, and for etching a legacy of peace that shall echo through the vault of heaven for all eternity.",
        "",
        "Go forth in bliss, valiant traveler, for the stars themselves sing of your deeds, and the light of your mercy shall illuminate the darkest corridors of the cosmos for generations to come.",
        "================================================================",
        "",
        "----------------------------------------------------------------",
        "- JACK'S MIGHTY QUEST (TM) -",
        "STABLE BUILD V1.0 | GAME ENGINE V1.0",
        "----------------------------------------------------------------",
        "",
        "",
        "================================================================",
        "EXECUTIVE PRODUCER & STUDIO LEAD",
        "================================================================",
        "",
        "Ibrahim Aayan Bin Abdulla",
        "",
        "",
        "================================================================",
        "DISTRIBUTION & MARKETING",
        "================================================================",
        "",
        "Fathmath Hudha Hussain",
        "Ibrahim Aayan Bin Abdulla",
        "",
        "",
        "================================================================",
        "BUSINESS MANAGEMENT",
        "================================================================",
        "",
        "Fathmath Hudha Hussain",
        "Ibrahim Aayan Bin Abdulla",
        "",
        "",
        "================================================================",
        "STORYBOARD & PLANNING",
        "================================================================",
        "",
        "Ibrahim Aayan Bin Abdulla",
        "Mohammed Husaan Hussain",
        "",
        "",
        "================================================================",
        "CUSTOM GRAPHICS",
        "================================================================",
        "",
        "Ibrahim Aayan Bin Abdulla",
        "SlimeOttie",
        "",
        "",
        "================================================================",
        "LOCALIZATION & TRANSLATION",
        "================================================================",
        "",
        "[ ENGLISH & DHIVEHI ]",
        "Mohammed Husaan Hussain",
        "Ibrahim Aayan Bin Abdulla",
        "",
        "[ JAPANESE ]",
        "Ibrahim Aayan Bin Abdulla",
        "Mei23",
        "",
        "[ KOREAN ]",
        "Ibrahim Aayan Bin Abdulla",
        "Heemin",
        "",
        "[ ARABIC ]",
        "Ibrahim Aayan Bin Abdulla",
        "RKK",
        "",
        "[ GERMAN, PORTUGUESE & SPANISH ]",
        "Ibrahim Aayan Bin Abdulla",
        "",
        "",
        "================================================================",
        "TYPOGRAPHY",
        "================================================================",
        "",
        "enikusu HG",
        "by Family Font Mart",
        "",
        "",
        "================================================================",
        "EXTERNAL ART ASSETS",
        "================================================================",
        "",
        "Explosions & Enemies",
        "by Ansimuz (ansimuz.itch.io)",
        "",
        "Parallax Backgrounds",
        "by Bongseng (bongseng.itch.io)",
        "",
        "Laser Bullets Pack 2020",
        "by Wenrexa (wenrexa.itch.io)",
        "",
        "Free Grasslands Tileset",
        "by Untied Games (untiedgames.itch.io)",
        "",
        "",
        "================================================================",
        "MUSIC PRODUCTION",
        "================================================================",
        "",
        "Ibrahim Aayan Bin Abdulla",
        "How2Bboss",
        "Mei23",
        "RKK",
        "SlimeOttie",
        "Furmilion",
        "Kawashin",
        "Shiru8bit",
        "",
        "Shoutout to the amazing DAWs & Music Trackers to make the chiptune bangers of this game possible:",
		"",
		"CHIPTUNE:-",
		"",
        "FamiStudio - By Mathieu Garcia (BleuBleu) and the FamiStudio Community",
		"",
        "FamiTracker - By jsr and the Retro Tracking Community",
		"",
		"CD AUDIO:-",
		"",
		"FL Studio - by Image-Line",
		"",
        "",
        "================================================================",
        "ADVANCED MUSIC PRODUCTION, SAMPLING & EDITING",
        "================================================================",
        "",
        "DJ Kokumo",
        "PixelForge07",
        "",
        "",
        "================================================================",
        "EXTERNAL AUDIO ASSETS",
        "================================================================",
        "",
        "SFX Laser Shoot 02",
        "by bolkmar (freesound.org/s/421704/)",
        "License: Creative Commons Attribution 4.0",
        "",
        "Explosion Outdoors (Medium)",
        "by EvanBoyerman (freesound.org/s/753843/)",
        "License: Creative Commons Attribution 4.0",
        "",
        "",
        "================================================================",
        "ADDITIONAL SUPPORTERS",
        "================================================================",
        "",
        "[ DEAREST MOTHER ]",
        "Shaira Hassan",
        "",
        "[ DEAREST SISTER ]",
        "Fathmath Hudha Hussain",
        "",
        "[ DEAREST BROTHER ]",
        "Amanullah Hassan Abdulla",
        "",
        "",
        "================================================================",
        "SPECIAL THANKS",
        "================================================================",
        "",
        "To everyone who made the development of Jack's Mighty Quest (TM) possible",
        "since Day 1! We couldn't have done this massive milestonic project without you all!",
        "",
        "Especially you, the player!",
        "We extend our utmost gratitude for reuniting the",
        "aspirations and dreams of many.",
        "",
        "----------------------------------------------------------------",
        "PRESENTED BY VORTEX (TM) INTERACTIVE",
        "----------------------------------------------------------------",
        "",
        "PEACE EMBRACES THE VALIANT",
        "LAURELS OF HARMONY!",
        "",
        "(c) 2026, 2027 Vortex Interactive Maldives.",
        "",
        "All rights reserved. Unauthorized duplication, reverse",
        "engineering, or distribution of this software is strictly",
        "prohibited under local and international copyright laws.",
        "",
        "",
        ""
    ];

    return _manifest;
}